apiVersion: v1 
kind: Service
metadata:
  name: ftps-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: metka
spec:
  selector:
    app: ftps
  loadBalancerIP: 192.168.99.100
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: port1
      port: 21
      targetPort: 21
    - protocol: TCP
      name: port2
      port: 21000
      targetPort: 21000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_image
        imagePullPolicy: Never
        ports:
          - containerPort: 21
          - containerPort: 21000